package rc

// Generated by https://quicktype.io

type Subscriptions struct {
	Update  []Subscription `json:"update"`
	Remove  []Subscription `json:"remove"`
	Success bool           `json:"success"`
}

type Subscription struct {
	Type          string      `json:"t"`
	Timestamp     string      `json:"ts"`
	Name          string      `json:"name"`
	Fname         interface{} `json:"fname"`
	RoomID        string      `json:"rid"`
	User          User        `json:"u"`
	Open          bool        `json:"open"`
	Alert         bool        `json:"alert"`
	Unread        int64       `json:"unread"`
	UserMentions  int64       `json:"userMentions"`
	GroupMentions int64       `json:"groupMentions"`
	UpdatedAt     string      `json:"_updatedAt"`
	ID            string      `json:"_id"`
}

func (c *Client) GetSubscriptions() ([]Subscription, error) {
	subs := &Subscriptions{}
	if err := c.c.get("/subscriptions.get", nil).JSON(&subs); err != nil {
		return nil, err
	}

	updates := subs.Update
	return updates, nil
}
